scrape_configs:
  - job_name: "node"
    scrape_interval: "1s"
    static_configs:
    - targets: ['mysql:9100']
  - job_name: "mysqld"
    scrape_interval: "1s"
    static_configs:
    - targets: ['mysql:9104']
